apiVersion: v1
kind: Service
metadata:
  name: my-external-service
spec:
  selector:
    app: my-server
  ports:
    - name: http
      protocol: TCP
      port: 88
      targetPort: 8080
  type: LoadBalancer
