# Nginx ConfigMap with another status code
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-canary-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          return 418 "I'm a teapot";
        }
      }
    }
---
# Nginx ConfigMap with delay
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-stable-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          return 200 "Hello from nginx";
        }
      }
    }
---

# Stable Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      track: stable
  template:
    metadata:
      labels:
        app: webapp
        track: stable
    spec:
      containers:
      - name: webapp
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-stable-config
---
# Canary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      track: canary
  template:
    metadata:
      labels:
        app: webapp
        track: canary
    spec:
      containers:
      - name: webapp
        image: nginx:1.15.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-canary-config

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80 