apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: load-generator
    image: python:3.9-slim
    command: 
    - /bin/sh
    - -c
    - |
      pip install requests
      python -c '
      import requests
      import time
      import logging
      from datetime import datetime

      logging.basicConfig(level=logging.INFO)
      logger = logging.getLogger(__name__)

      TARGET_URL = "http://webapp-service"  # possible values: http://my-service, http://webapp-service
      INTERVAL_MS = 100

      while True:
          start_time = time.time()
          try:
              response = requests.get(TARGET_URL)
              end_time = time.time()
              response_time = (end_time - start_time) * 1000  # Convert to milliseconds
              logger.info(f"Response: {response.status_code}, {response.text[:100]}, Time: {response_time:.2f}ms")
          except Exception as e:
              logger.error(f"Error: {str(e)}")
          
          time.sleep(INTERVAL_MS / 1000)  # Convert ms to seconds
      '
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
