apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx:1.14.2
        ports:
        - containerPort: 80 
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: fixed-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
