apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webserver
  labels:
    app: demo-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-webserver
  template:
    metadata:
      labels:
        app: demo-webserver
    spec:
      containers:
      - name: demo-webserver
        image: docker.io/balazska/seminar-3-webserver:v3
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 150m
            memory: 128Mi
          requests:
            cpu: 150m
            memory: 128Mi