{
 "title": "Demo Webserver",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AVG HTTP Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(seminar_http_requests_total{kubernetes_pod_name=~\"demo-webserver.*\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"demo-webserver.*\"}[2m])) *1000"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_usage_bytes{pod=~\"demo-webserver.*\"}[2m])) / 1024"
    }
   ]
  }
 ]
}