global:
  scrape_interval: 15s
  evaluation_interval: 15s
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-pushgateway:
  enabled: false
server:
  service:
    type: NodePort
    nodePort: 30001
extraScrapeConfigs: >
  - job_name: demo-webserver
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: demo-webserver
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
    static_configs:
      - targets: ['localhost:8080']
